### ISSUE TITLE
Zadávání výsledného skóre z více zařízení

### ISSUE THREAD

**Issue by vosecek** [vosecek/catcher#15]
Při ručním nastavení skóre je třeba přidat kontrolu na duplicitu přidávaných bodů - nějak ověřovat před samotným vygenerováním bodů, zda to už někdo před pár vteřinami neudělal. Současná situace vygeneruje duplicitní věci.

**Comment by horalstvo** [comment]
Mi to prijde jako moc chytre, proste neco zadas, tak to zadas, na skore
uvidis, ze nesedi a prebytecny bod smazes. V realu bych pak spis sel
cestou, ze se pred turnajem prideli clovek zodpovedny za odskorovani daneho
zapasu... takze takove dvojskorovani nebude vznikat.

2013/10/15 Jiří Voseček notifications@github.com

**Comment by vosecek** [comment]
Ono se může v reálu stát, že zadají dva správci turnaje výsledek jednoho zápasu zároveň. Když se aplikace použije pouze jako záznam výsledků, tak to nastat může a budeš muset mazat polovinu bodů. Řešením by ale asi byla úprava systému zadávání konečného výsledku, teď se body posílají jednotlivě (vytváří se v aplikaci) a znamená to celkem pomalý proces. Pokud by se poslal jen výsledek a server by body vyrobil a aplikace jen stáhla, tak je to vyřešený.

**Comment by vosecek** [comment]
Upraveno. Body se vytváří na serveru podle požadavku na cílové skóre. Následně si klient požádá o aktuální stav a stáhnou se body v jednom requestu - urychlení komunikace a snížení datového přenosu.
