### ISSUE TITLE
Odstranění horní lišty

### ISSUE THREAD

**Issue by vosecek** [vosecek/catcher#5]
http://www.sencha.com/forum/showthread.php?259817-3.1.0.256-Strange-Android-Titlebar-on-native-Apps/page2

**Comment by horalstvo** [comment]
staci postupovat podle odkazu, tedy do st-res/android/AndroidManifest.xml pridat android:theme do nasledujiciho radku:

<application android:icon="@drawable/icon" android:label="%s" android:theme="@android:style/Theme.NoTitleBar">

Otestovano, zatim nevim, jak to pridat primo do aplikace, aby clovek nemusel menit nastaveni buildu, ktere je v jadru externi od aplikace.

**Comment by vosecek** [comment]
To asi možný není, ale jednoduše se upraví ta šablona v SenchaCMD a dál se to nemusí řešit. Takže asi v pohodě.
